spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 200MB
  jpa:
    hibernate:
      ddl-auto: create-drop
      naming:
        # CamelCase -> SnakeCase
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: 'true'
        show_sql: 'true'
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /db
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
jwt:
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK
cloud:
  aws:
    s3:
      bucket: jkboston
    credentials:
      access-key: AKIA4OTF2RFBNW42IR5C
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false